spring.application.name=Spring_AI

server.port=8081

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flas


#Groq api key
spring.ai.openai.api-key=${GROQ_API_KEY}