spring.application.name=Spring_AI

server.port=8081

# ===========================
# Google Gemini
# ===========================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

# ===========================
# Groq (OpenAI Compatible)
# ===========================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile

# ===========================
# Disable auto ChatClient
# ===========================
spring.ai.chat.client.enabled=false